modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="lambdynforge" #mandatory
version="${file.jarVersion}" #mandatory
displayName="LambDynForge" #mandatory
logoFile="" #optional png
authors="" #optional
description='''
Forge port of Lambs Dynamics Lights
'''
[[dependencies.lambdynforge]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.lambdynforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="AFTER"
    side="BOTH"
